halogen 1.0.0
slamdata/purescript-halogen-menu pull request #23
Opened 2017-02-07 17:13 UTC by cryogenian

@natefaubion Please review

2017-02-07 18:24 UTC, natefaubion requested changes

2017-02-07 18:24 UTC, natefaubion commented on src/Halogen/Menu/Component.purs
> +  , receiver: \submenus → Just $ H.action $ Set { chosen: Nothing, submenus }
If you are resetting `chosen` to Nothing, this means every time a parent renders, the selection will be cleared.

2017-02-08 14:22 UTC, cryogenian commented
+ `receiver: const Nothing`

I need a bit more playing with inputs to see how this could be done prettier.

2017-02-08 15:07 UTC, natefaubion approved these changes

2017-02-08 15:07 UTC, merged